apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: argo-demo
  namespace: demo

spec:

  replicas: 1

  selector:
    matchLabels:
      app: argo-demo

  template:

    metadata:
      labels:
        app: argo-demo

    spec:

      containers:

      - name: argo-demo

        image: 638111422814.dkr.ecr.us-east-1.amazonaws.com/argo:094d9f69d81bb363af483b26e14a01b00454d6e2

        imagePullPolicy: Always

        ports:

        - containerPort: 3000

  strategy:

    blueGreen:

      activeService: argo-demo-active

      previewService: argo-demo-preview

      autoPromotionEnabled: true

      previewReplicaCount: 1
